version: '3.9'

services:
  database_itaros:
    image: postgres
    container_name: database_itaros
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=itafosros
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: itaros
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/app
    links:
      - database_itaros
    depends_on:
      - database_itaros

volumes:
  pgdata: 
    driver: local
